{% set name = "napari-laptrack" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-laptrack-{{ version }}.tar.gz
  sha256: 5cf84b735954271e97d98986a73210dbd50aa1c4ae285eadf2bc3c13ae56958f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - laptrack >=0.10.0
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer
    - napari-tools-menu
    - napari-skimage-regionprops >=0.9.0
    - numpy
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - napari_laptrack
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-laptrack
  summary: Tracking particles in Napari, based on the LapTrack library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
